project:
  type: website

website:
  title: "ì˜¤ë Œì§€ ë§¨ìˆ€ğŸŠ"
  site-url: https://orangemansion.com
  description: "ê·¤ í–¥ ê°€ë“í•œ, ì˜¤ë Œì§€ ë§¨ìˆ€ì…ë‹ˆë‹¤."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/chichead
      - icon: instagram
        href: https://www.instagram.com/ahnhyemin
      - icon: linkedin
        href: https://www.linkedin.com/in/anhyemin
  google-analytics: G-YZCBLF5F53
format:
  html:
    theme: 
      - styles.css
      - custom.scss


