project:
  type: website

website:
  title: "ì˜¤ë Œì§€ ë§¨ìˆ€ğŸŠ"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chichead
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: styles.css
      dark: darkly

editor: visual

about:
  template: jolla

