project:
  type: website

website:
  title: "ğŸŠì˜¤ë Œì§€ë§¨ìˆ€"
  site-url: https://orange-mansion.com
  description: "ê·¤ í–¥ ê°€ë“í•œ, ì˜¤ë Œì§€ ë§¨ìˆ€ì…ë‹ˆë‹¤."
  favicon: fabicon.png
  navbar:
    left:
      - text: "POSTS"
        file: index.qmd
      - text: "NEWS"
        file: news.qmd
      - text: "DIARY"
        file: daily.qmd

    right:
      - text: "ABOUT"
        file: about.qmd
      - icon: instagram
        href: https://www.instagram.com/ahnhyemin
      - icon: github
        href: https://github.com/chichead
      - icon: linkedin
        href: https://www.linkedin.com/in/anhyemin
  google-analytics: G-YZCBLF5F53
  cookie-consent: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
format:
  html:
    smooth-scroll: true
    theme: 
      - styles.css
      - custom.scss
    mainfont: Pretendard
    toc: true
    toc-location: right
    code-link: true
