project:
  type: website

website:
  title: "ì˜¤ë Œì§€ ë§¨ìˆ€ğŸŠ"
  site-url: https://orange-mansion.com
  description: "ê·¤ í–¥ ê°€ë“í•œ, ì˜¤ë Œì§€ ë§¨ìˆ€ì…ë‹ˆë‹¤."
  navbar:
    right:
      - text: "Blog"
        file: index.qmd
      - text: "Daily"
        file: daily.qmd
      - text: "About"
        file: about.qmd
      - icon: instagram
        href: https://www.instagram.com/ahnhyemin
      - icon: github
        href: https://github.com/chichead
      - icon: linkedin
        href: https://www.linkedin.com/in/anhyemin
  google-analytics: G-YZCBLF5F53
  cookie-consent: true
format:
  html:
    smooth-scroll: true
    theme: 
      - styles.css
      - custom.scss
    toc: true
    toc-location: right
    code-link: true


